before_script:
  - ruby -v
  - which ruby
  - sudo apt-get install libicu-dev -y
  - gem install bundler --no-ri --no-rdoc
  - bundle install

rspec:
  script:
  - bundle exec rake test
  tags:
    - ruby